### PR TITLE
[Feature Request]: Adding preview of links shared to chat with click property

### LINKED ISSUE #119: [Feature Request]: Adding preview in links shared to chat with click property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The main problem is to make the links shared in the chat clickable and also preview it in the chat like discord or LinkedIn, twitter, Instagram platform does.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by yashksaini-coder**
- Fixes #119 

## 📋 Description
The main problem is to make the links shared in the chat clickable and also preview them inside the chat like discord or LinkedIn, twitter, Instagram platform does.

## 🔨 Changes Made

This pull request introduces a new feature to extract and display link previews in messages. It includes changes to both the backend and frontend to support this functionality.

### Backend Changes:

* [`backend/controllers/messageControllers.js`](diffhunk://#diff-fa9564597aa48506405731042d29d766c4003c7e40a61419bcac39b790867818R26-R44): Added logic to extract URLs from message content and fetch link previews using an external API. These previews are then included in the message object.
* [`backend/models/messageModel.js`](diffhunk://#diff-5f64810f13c2815a94dfb8d3a63123c4580fa4c82a56f462c51eb8800b25af84R9-R14): Updated the message schema to include a new field for storing link previews, which contain title, description, URL, and image.
* [`backend/package.json`](diffhunk://#diff-495707834ca4b862f9acdfbac70d279023d2c059da13db59594e61ed3354fed5R21): Added the `node-fetch` package to enable fetching link previews from an external API.

### Frontend Changes:

* [`frontend/src/components/ScrollableChat.js`](diffhunk://#diff-4712c73344afadcfc8f986474c7037ef40e37176f4ce05f1e6fc70254a87cbeeR4-R79): Modified the `ScrollableChat` component to display link previews within messages. This includes rendering the previews with appropriate styling and ensuring the message content appears below the previews.
* [`frontend/package.json`](diffhunk://#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655R27-R28): Added the `stream-chat` and `stream-chat-react` packages to support the new chat features.

### Summary of Changes

**Backend:**
- Updated sendMessage in messageControllers.js to extract URLs and fetch link previews.
- Modified messageModel.js to include a linkPreviews field.

**Frontend:**
- Updated the message rendering logic to display link previews.

- #119 

## 🔨 Screen Shots OR Short videos of working

[talktrove-119.webm](https://github.com/user-attachments/assets/0e1659d4-5815-4ab3-8f5d-2da3fbdfbb94)

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] My code follows the style guidelines of this project.
- [X] Read Contributing.md

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [X] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

---

> [!NOTE]
> Make sure to replace `YOUR_API_KEY` with your actual API key for the link preview service from [here](https://my.linkpreview.net/)
> You may need to install `node-fetch` in your backend if it's not already included

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@kartikay-bigsteps @Sibam-Paul Review this PR, and assign it to me

**Comment by yashksaini-coder** [comment]
@Sibam-Paul there is an error in vercel deployment is there something wrong on my code ?

**Comment by Sibam-Paul** [comment]
Wait seeing

**Comment by yashksaini-coder** [comment]
@Sibam-Paul all changes pushed

**Review by Sibam-Paul — APPROVED** [review]
image

locally tested

**Comment by Sibam-Paul** [comment]
closes - #119

**Pull request merged**
