### PR TITLE
Revert "methods are made for emai template and email confirigation using gmail smtp server "

### PR DESCRIPTION
**Pull request by Sibam-Paul**
Reverts kartikayasijaa/talk-trove#22

Please make .env files 
Please make the frontend part then I will merge

### CODE REVIEW

**Comment by praveenarjun** [comment]
does my pr is merged or have u made any changes

**Comment by Sibam-Paul** [comment]
yes merged

**Comment by Sibam-Paul** [comment]
Its a test PR

**Comment by praveenarjun** [comment]
ok. how much time does it takes for updating my leaderboard in gssoc i am curious to see my improved rank 
And Thank you for Merging

**Pull request merged**
