### PR TITLE
Removed default react icon from website

### LINKED ISSUE #6: [UI]- Remove react favicon
remove the react favicon 
Screenshot 2024-10-02 at 9 12 00 PM

### PR DESCRIPTION
**Pull request by Abheeshta-P**
## 📋 Description

This PR addresses the use of the React logo as the favicon, which can be seen as unprofessional for large organizations. The favicon has been removed.

## 🔨 Changes Made

- From index.html removed favicon link
- fixes #6

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ✅] My code follows the style guidelines of this project.
- [✅ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [✅ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #6

## 📸 Screenshots 
image

---

### CODE REVIEW

**Comment by Sibam-Paul** [comment]
Can u add a favicon to it will be nice @Abheeshta-P

**Comment by Abheeshta-P** [comment]
@Sibam-Paul Do you have any logo??

**Comment by Sibam-Paul** [comment]
rn not but create it on yr own

**Review by Sibam-Paul — APPROVED** [review]

**Comment by Sibam-Paul** [comment]
@Abheeshta-P Create a issue we are goin to make it like a slack where we can discuss doubts within the project

**Comment by Sibam-Paul** [comment]
@Abheeshta-P The react icon is still prevailing

**Comment by Sibam-Paul** [comment]
See 
image

**Comment by Abheeshta-P** [comment]
@Sibam-Paul 
image
just check the pr i have sent just now its working in my local server, If it persists let me know!

**Comment by Abheeshta-P** [comment]
@Sibam-Paul Also could you please add hactober label to this! it would be helpful

**Pull request merged**
