### PR TITLE
Fix emoji thing on single chat

### LINKED ISSUE #80: [BUG] Emoji Bug
When we add some text, and then add an emoji. The text dissappears.

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #80
Screenshot 2024-10-15 at 12 48 05 AM

### CODE REVIEW

**Comment by Sibam-Paul** [comment]
closes - #80

**Review by MastanSayyad — COMMENTED** [review]
Hi @Sibam-Paul @kartikayasijaa 

level 2 does not make sense to this PR, its is minor change, can you please remove the labels?

image

**Comment by shubhagarwal1** [comment]
> Hi @Sibam-Paul @kartikayasijaa
> 
> level 2 does not make sense to this PR, its is minor change, can you please remove the labels?
> 
> image

Hey @MastanSayyad well that was a esseita bug that was causing no text after emoji, but i agreee that make no sense for level 2. Great revewing, appreciate your efforts.

**Comment by kartikayasijaa** [comment]
@MastanSayyad I would not judge this change on the basis of lines changed in code. I would judge it on the basis of its impact. Also it's not an easy task to figure out which exact line would cause the issue.
I think @shubhagarwal1 has done a great job here, and `level2` should be there.

**Comment by MastanSayyad** [comment]
Hi @kartikayasijaa, 

As the Program Manager of GSSoC, I want to clarify my approach and reason for adjusting the level on this PR. My role includes reviewing all contributors to ensure that our scoring guidelines are applied fairly and consistently, especially for top contributors on the leaderboard, I review the code first then only take a decision. We are doing this with everyone but closely to top 50 and deeply for top 3 as only they have the most impact on the leaderboard

While I understand and respect your evaluation based on impact, this PR involves a relatively minor change: it appends `emojiObject.emoji` to `prevMessage` by modifying the function to take the previous state as an argument. 



image



While this change is helpful, it’s a single function adjustment and aligns more closely with a level1 rating (10 points) given its simplicity, Given that this is a minimal code change and @shubhagarwal1 is already ranked 1, awarding any points here would create an imbalance on the leaderboard. Our focus is to maintain consistency, particularly for top contributors, where even small adjustments can impact the overall rankings significantly.


Additionally, it’s important that PMs have collaborator access to facilitate efficient review. It was mentioned in the selection emails, and I’ve reached out a few times regarding this. With access, we can promptly address tasks, maintain transparency, and balance the leaderboard effectively.



Thank you for your understanding,  @sanjay-kv and @hemu21 I may need your further assistence in this matter and this repository

**Comment by kartikayasijaa** [comment]
I have changed the label to `level1`. But I still wants to understand, why we are deciding levels on the basis of:
- Number of lines changed
- Postion on leaderboard

Why we are not considering these things:
- Effort put in understanding the issue
- Debugging
- Lack of context of project, but still able to solve the bug.
- Collaboration and Communication
- Consistency
- Quality of Code

@MastanSayyad @Hemu21 @sanjay-kv I think this issue needs to be addressed.

**Comment by Wahid7852** [comment]
I believe there has been a misunderstanding, whilst your points are correct @kartikayasijaa, we are also considering that the top contributors be balanced out so that it creates a sense of competition for the rest of the competitors.

**Pull request merged**
